### ISSUE TITLE
Fvwm-menu-desktop fails if used with --get-menus

### ISSUE THREAD

**Issue by lgsobalvarro** [fvwmorg/fvwm3#234]
If I run
`fvwm-menu-desktop --get-menus all`

Or

`fvwm-menu-desktop --get-menus desktop`

I get the following:

```
Traceback (most recent call last):
  File "/usr/local/bin/fvwm-menu-desktop", line 889, in <module>
    main()
  File "/usr/local/bin/fvwm-menu-desktop", line 470, in main
    parsemenus(menulist, desktop, desktop_entries)
  File "/usr/local/bin/fvwm-menu-desktop", line 746, in parsemenus
    parsemenu(xdg.Menu.parse(menu), name, title, desktop_subentries)
  File "/usr/lib/python3.8/site-packages/xdg/Menu.py", line 1128, in parse
    return XMLMenuBuilder(debug).parse(filename)
  File "/usr/lib/python3.8/site-packages/xdg/Menu.py", line 632, in parse
    menu = self.parse_menu(tree.getroot(), filename)
  File "/usr/lib/python3.8/site-packages/xdg/Menu.py", line 650, in parse_menu
    self.parse_node(node, filename, menu)
  File "/usr/lib/python3.8/site-packages/xdg/Menu.py", line 659, in parse_node
    menu = self.parse_menu(child, filename)
  File "/usr/lib/python3.8/site-packages/xdg/Menu.py", line 650, in parse_menu
    self.parse_node(node, filename, menu)
  File "/usr/lib/python3.8/site-packages/xdg/Menu.py", line 682, in parse_node
    parent.Rules.append(self.parse_rule(child))
  File "/usr/lib/python3.8/site-packages/xdg/Menu.py", line 759, in parse_rule
    return Rule(type, tree)
  File "/usr/lib/python3.8/site-packages/xdg/Menu.py", line 421, in __init__
    self.code = compile(self.expression, '<compiled-menu-rule>', 'eval')
ValueError: Name node can't be used with 'True' constant
```
This issue seems to affect FVWM2 as well.

**Comment by ThomasAdam** [comment]
Hi @lgsobalvarro,

I seem to recall a brief conversation about this on IRC, with @somiaj?  @somiaj -- is this an actual problem we need to solve, do you know?

**Comment by somiaj** [comment]
My only comment was 'it works for me', and I didn't have time to look at why python is not liking it. Since I'm using python 3.7, unsure if there is some change in python 3.8, or something on lgsobalvarro's system causing this ValueError.

**Comment by ThomasAdam** [comment]
Okey dokey.  @lgsobalvarro, which python version are you using which shows this error?

**Comment by lgsobalvarro** [comment]
Python 3.8.5

**Comment by ThomasAdam** [comment]
Hi @lgsobalvarro 

Is this issue still a problem?

**Comment by lgsobalvarro** [comment]
Yes. The problem continues with the exact same error when I run fvwm-menu-desktop --get-menus all

Tested with Fvwm3 1.0.1 (1.0.0-42-g264eaf1e)

**Comment by lgsobalvarro** [comment]
This seems to work now fine.
I didn't touch anything on my config. 
Seems like it had something to do with the way python was being packaged or something. Looks like the most recent python update changed this.

Seems @somiaj was in the right track.

I'm closing this issue then :)
