### ISSUE TITLE
Zero-size malloc on ta/randr branch

### ISSUE THREAD

**Issue by io7m** [fvwmorg/fvwm3#5]
Hello.

The attached config file will result in an `fvwm3: malloc: zero size.` error and abnormal exit.

[config.txt](https://github.com/fvwmorg/fvwm3/files/3492459/config.txt)

```
(gdb) bt
#0  0x00007ffff699df90 in exit () at /usr/lib/libc.so.6
#1  0x00007ffff6a59eb9 in  () at /usr/lib/libc.so.6
#2  0x00007ffff6a59ff8 in  () at /usr/lib/libc.so.6
#3  0x000055555564261d in xmalloc (length=0) at safemalloc.c:27
#4  0x00005555555dc77f in CMD_All (cond_rc=0x7fffffffdde8, exc=0x5555556e9970, action=0x555555711764 "PlaceAgain")
    at conditional.c:1611
#5  0x00005555555eed51 in __execute_function
    (cond_rc=0x0, exc=0x555555711a10, action=0x5555556475c5 "All PlaceAgain", exec_flags=0 '\000', args=0x0, has_ref_window_moved=0)
    at functions.c:639
#6  0x00005555555f0159 in execute_function
    (cond_rc=0x0, exc=0x555555711a10, action=0x5555556475c5 "All PlaceAgain", exec_flags=0 '\000') at functions.c:1302
#7  0x00005555555f02a6 in execute_function_override_window
    (cond_rc=0x0, exc=0x0, action=0x5555556475c5 "All PlaceAgain", exec_flags=0 '\000', fw=0x0) at functions.c:1352
#8  0x00005555555980db in HandleRRScreenChangeNotify (e=0x7fffffffe010) at events.c:1798
#9  0x000055555559cb44 in dispatch_event (e=0x7fffffffe010) at events.c:4122
#10 0x000055555559ce0d in HandleEvents () at events.c:4231
#11 0x00005555555c8061 in main (argc=3, argv=0x7fffffffe498) at fvwm3.c:2597

```

The existing FVWM 2.6.8 release prints a warning but continues running.

**Comment by io7m** [comment]
```
$ uname -a
Linux almond.int.arc7.info 5.2.8-arch1-1-ARCH #1 SMP PREEMPT Fri Aug 9 21:36:07 UTC 2019 x86_64 GNU/Linux
```

**Comment by ThomasAdam** [comment]
I believe this to be fixed on master now.  Please can you try that for me?
